version: 0.2  
  
env:  
  variables:  
    TF_VERSION: "0.12.8" 
  
phases:  
  
  install:  
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      - sudo yum -y install terraform  
      # - cd /usr/bin  
      # - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/3.15.0/terraform_3.15.0_linux_amd64.zip"  
      # - unzip -o terraform.zip  
  
  build:  
    commands:
      - echo "COMMANDS ~~~~~~~~~~~~~~~~~~~~"
      - ls      
     # - cd "$CODEBUILD_SRC_DIR"  
    #  - sed -i -e "s/{{ENV}}/$TF_VAR_ENV/" terraform.tf  
      - terraform init -no-color  
      - terraform apply -no-color  
  
  post_build:  
    commands:  
      - echo "terraform apply  completed"